### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by tomberek**
Might be helpful for someone.

### CODE REVIEW

**Comment by jmcorgan** [comment]
Thanks.

It's not clear where you would be running the shell fragment you list, though.  Are you referring to the verification of the stock ISO signature?

This part of the script system already does the key fetch for you:

https://github.com/gnuradio/gnuradio-livesdr/blob/livesdr/bin/get-stock-iso#L28

...but is missing the part about editing the trust level (which you wouldn't want automated anyway.)

**Comment by tomberek** [comment]
Yes, that's what I meant. Just to help someone go through adding whatever trust is needed.

**Comment by jmcorgan** [comment]
Got it.  So, the GNU Radio side of things is maintained as a branch 'livesdr', which incorporates all the GR specific stuff.  The master branch is maintained in the home repository jmcorgan/ubuntu-remaster. I'll go ahead and apply this commit over there and then merge up and push the new master and livesdr here.

Thanks.

**Comment by jmcorgan** [comment]
I cherry-picked this commit onto the master branch and merged up.

**Pull request closed without merging**
