### PR TITLE
Ubuntu updated to 14.04.3

### PR DESCRIPTION
**Pull request by jynik**
It appears that the Ubuntu 14.04 release has been bumped, and the 14.04.2 iso link now 404's.

### CODE REVIEW

**Comment by jmcorgan** [comment]
Have you actually gone through a full build with this?  The change from .2 to .3 happened right after I did the 3.7.8 release.  I did a quick check on the master branch and it created something that wouldn't boot, but I didn't have time to diagnose it before heading off for three weeks on the road.

**Comment by jynik** [comment]
I am having boot related issues, but thought something in my environment
changed as I've been prepping a number of changes. I'd say kill this PR
then and we'll have to look into what changed..

I'd say

**Comment by jmcorgan** [comment]
Ok.  I'll start in to this tomorrow AM, thanks.

**Comment by jmcorgan** [comment]
Looks like Canonical has overhauled the casper boot script that finds and mounts the root and overlay filesystems durint initrd.  The livesdr system uses a customization of this script to enable encrypted ISO images, so I'll have to forward port my changes to the new one.

**Comment by jmcorgan** [comment]
This is now working on the master/basic/livesdr branches.

**Pull request closed without merging**
